// Tech Inventory Table Field IDs
export const TECH_INVENTORY_FIELDS = {
  NAME: 'fldCPXmtYCgZT7Kx7',
  CATEGORY: 'fldOtQNxP2dbFObUe',
  QUANTITY: 'fldKtjYbCjlpGfeCD',
  IP_ADDRESS: 'fldtp9ylfpKkgMNZD',
  MAC_ADDRESS: 'fldpLpmVTJ8XFvCwZ',
  UPSTREAM: 'fld5fH4e3favSS0Z0',
  SWITCH: 'fldbiST3nw6CP1tlf',
  VIDEO_INPUT: 'fldAfEljfA5MTRrxX',
  SERIAL_NUMBER: 'fldgapOFiDZmZBFF9',
  MAKE: 'fld2CaJU46TyKEiB3',
  MODEL: 'fldKq7unH0RdvXu6V',
  FIRMWARE_VERSION: 'fldHpFU5vlI2LiAyO',
  LAST_UPDATED: 'fld1kf3xf0uqkOV82',
  PASSWORD: 'fldOkiXZpDAmzdtKt',
  DMX_UNIVERSE: 'fldIit9m0HJeuwtM8',
  NOTES: 'fldPTdV9hRybE8qGf',
  DMX: 'fld1p9vlbPmqFx1c5',
  USER_NAME: 'fldiJ70FcdwH0VzRV',
  BARCODDED_ITEM: 'fldhImH63FDwKkp52',
  NUMBER_OF_ITEMS: 'fld9X3UikIfYQPtCM',
  PHOTO: 'fldh2lBxOiVfIP0Ap',
  PACKAGES: 'fldRE8hgt01XE4dCM',
  DESCRIPTION: 'fldBzNrl6YbLbE348',
  PRICE: 'fldHDjZy3Q8hyeGHZ',
  TWO_DAY_PRICE: 'fldYo1aIJqxlU7STW',
  WEEK_PRICE: 'fldmzRoAUtC60KQRq',
  FIELD_26: 'fld0gqhqNXiSzcqEv',
  COMPUTED_QUANTITY: 'fldw6rhXXSTQ7QUxI',
};

// Packages Table Field IDs
export const PACKAGES_FIELDS = {
  NAME: 'fldv9JIvwmmMoPXBQ',
  DAY_RATE: 'fld8E2dHwqliPk8Fw',
  TWO_DAY_RATE: 'fldDLG27ngpGGqDtd',
  WEEKLY_RATE: 'fldQ9YXF8qTi43Rx2',
  CONTENTS: 'fld1ll694RNSXAMRo',
  DESCRIPTION: 'fldaxI4HEPHdEVbT9',
  NOTES: 'fld1PDaB8g0rlC1VT',
  CATEGORY: 'fldiupsF4lFIDuo3W',
}; 